### ISSUE TITLE
The possibility of providing MTProto support

### ISSUE THREAD

**Issue by coremodmc** [go-crare/crare#1]
When migrating the `telebot-exp` to `Crare`, someone asked me a suggestion to use `MTProto`. A few days later, now, I think `Crare` can provide a new `Poller` for `MTProto`, or provides a dedicated sub -bag, which will not affect the `Crare` API.

I am evaluating the possibility of this operation. It may cause some changes to the `Poller` interface, and may need to introduce additional subcuns to support additional APIs.

**Comment by coremodmc** [comment]
It seems to be possible, but I found that Poller may need to be completely rewritten, or reimplemented for all API methods.

I'll try to do it a little first, in a new branch...

**Comment by 3JoB** [comment]
My decision was to split it into two packages and share the same interface. In mtproto, you can use a Proto() method to call additional methods, which makes it possible to quickly switch between mtproto and botapi. But this may cause some extra work, give it a try first.

**Comment by coremodmc** [comment]
Poor API and documentation, it's unreachable and related processes have been cancelled.
